"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { motion } from "framer-motion";
import {
  CalendarDays,
  Users,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  UserCheck,
  Cloud,
  Save,
  Wifi,
  WifiOff,
  RefreshCw,
  User,
} from "lucide-react";

/**
 * Vercel 可部署版说明
 *
 * 1. 新建 Next.js 项目（App Router）
 * 2. 将本文件保存为：app/page.tsx
 * 3. 安装依赖：
 *    npm install @supabase/supabase-js framer-motion lucide-react
 * 4. 确保项目里已有 shadcn/ui 组件：card、button、input、badge、checkbox、alert
 * 5. 在 Vercel / 本地 .env.local 中配置：
 *    NEXT_PUBLIC_SUPABASE_URL=...
 *    NEXT_PUBLIC_SUPABASE_ANON_KEY=...
 * 6. Supabase 需准备的 SQL：
 *
 * create table if not exists public.meeting_availability (
 *   id bigint generated by default as identity primary key,
 *   poll_id text not null,
 *   participant_name text not null,
 *   owner_user_id uuid not null,
 *   date_key text not null,
 *   slots jsonb not null default '[]'::jsonb,
 *   created_at timestamptz not null default now(),
 *   updated_at timestamptz not null default now(),
 *   unique (poll_id, participant_name, date_key)
 * );
 *
 * create index if not exists idx_meeting_availability_poll_id
 *   on public.meeting_availability (poll_id);
 *
 * create index if not exists idx_meeting_availability_owner_user_id
 *   on public.meeting_availability (owner_user_id);
 *
 * alter table public.meeting_availability enable row level security;
 *
 * create policy "meeting availability is readable by everyone"
 * on public.meeting_availability
 * for select
 * to anon, authenticated
 * using (true);
 *
 * create policy "users can insert only their own rows"
 * on public.meeting_availability
 * for insert
 * to authenticated
 * with check (owner_user_id = auth.uid());
 *
 * create policy "users can update only their own rows"
 * on public.meeting_availability
 * for update
 * to authenticated
 * using (owner_user_id = auth.uid())
 * with check (owner_user_id = auth.uid());
 *
 * create policy "users can delete only their own rows"
 * on public.meeting_availability
 * for delete
 * to authenticated
 * using (owner_user_id = auth.uid());
 *
 * alter publication supabase_realtime add table public.meeting_availability;
 *
 * 7. 在 Supabase Auth 中启用 Anonymous sign-ins
 * 8. 可选：通过 URL 传 poll 参数，例如 ?poll=team-sync-1
 */

type AvailabilityMap = Record<string, Record<string, string[]>>;
type PersonAvailability = Record<string, string[]>;

type MeetingRow = {
  poll_id: string;
  participant_name: string;
  owner_user_id: string;
  date_key: string;
  slots: string[];
};

const TIME_SLOTS = [
  { id: "morning", label: "上午 09:00–12:00" },
  { id: "afternoon", label: "下午 13:00–17:00" },
  { id: "evening", label: "晚上 18:00–21:00" },
] as const;

const WEEKDAYS = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"];
const DEFAULT_POLL_ID = "team-meeting-demo";

function getPollId(): string {
  if (typeof window === "undefined") return DEFAULT_POLL_ID;
  const params = new URLSearchParams(window.location.search);
  return params.get("poll")?.trim() || DEFAULT_POLL_ID;
}

function getStorageKey(pollId: string): string {
  return `meeting-scheduler-local-${pollId}`;
}

function getProfileKey(pollId: string): string {
  return `meeting-scheduler-profile-${pollId}`;
}

function createSupabaseBrowserClient(): SupabaseClient | null {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!url || !anonKey) return null;
  return createClient(url, anonKey);
}

function formatDateKey(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function formatDateCN(dateKey: string): string {
  const [y, m, d] = dateKey.split("-");
  const date = new Date(Number(y), Number(m) - 1, Number(d));
  const weekdayMap = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];
  return `${y}年${m}月${d}日 ${weekdayMap[date.getDay()]}`;
}

function getMonthMatrix(currentMonth: Date): Date[][] {
  const year = currentMonth.getFullYear();
  const month = currentMonth.getMonth();
  const firstDay = new Date(year, month, 1);
  const firstWeekday = (firstDay.getDay() + 6) % 7;
  const startDate = new Date(year, month, 1 - firstWeekday);
  const days: Date[] = [];

  for (let i = 0; i < 42; i += 1) {
    const date = new Date(startDate);
    date.setDate(startDate.getDate() + i);
    days.push(date);
  }

  const weeks: Date[][] = [];
  for (let i = 0; i < days.length; i += 7) {
    weeks.push(days.slice(i, i + 7));
  }
  return weeks;
}

function slotLabelById(slotId: string): string {
  return TIME_SLOTS.find((slot) => slot.id === slotId)?.label || slotId;
}

function normalizePersonAvailability(input: unknown): PersonAvailability {
  if (!input || typeof input !== "object") return {};
  const next: PersonAvailability = {};

  Object.entries(input as Record<string, unknown>).forEach(([dateKey, slots]) => {
    if (!Array.isArray(slots)) return;
    const cleaned = Array.from(new Set(slots.filter(Boolean))).sort() as string[];
    if (cleaned.length > 0) next[dateKey] = cleaned;
  });

  return next;
}

function inflateRowsToAvailability(rows: Array<{ participant_name: string; date_key: string; slots: string[] }>): AvailabilityMap {
  const result: AvailabilityMap = {};

  rows.forEach((row) => {
    if (!row?.participant_name || !row?.date_key) return;
    if (!result[row.participant_name]) result[row.participant_name] = {};
    result[row.participant_name][row.date_key] = Array.isArray(row.slots)
      ? Array.from(new Set(row.slots)).sort()
      : [];
  });

  return result;
}

function arePersonAvailabilityEqual(a: PersonAvailability, b: PersonAvailability): boolean {
  const aKeys = Object.keys(a).sort();
  const bKeys = Object.keys(b).sort();
  if (aKeys.length !== bKeys.length) return false;

  for (let i = 0; i < aKeys.length; i += 1) {
    if (aKeys[i] !== bKeys[i]) return false;
    const aSlots = [...(a[aKeys[i]] || [])].sort();
    const bSlots = [...(b[bKeys[i]] || [])].sort();
    if (aSlots.length !== bSlots.length) return false;
    for (let j = 0; j < aSlots.length; j += 1) {
      if (aSlots[j] !== bSlots[j]) return false;
    }
  }

  return true;
}

function flattenPersonAvailability(personAvailability: PersonAvailability, participantName: string, ownerUserId: string, pollId: string): MeetingRow[] {
  return Object.entries(personAvailability).map(([date_key, slots]) => ({
    poll_id: pollId,
    participant_name: participantName,
    owner_user_id: ownerUserId,
    date_key,
    slots: [...slots].sort(),
  }));
}

export default function Page() {
  const [pollId, setPollId] = useState(DEFAULT_POLL_ID);
  const [currentMonth, setCurrentMonth] = useState<Date>(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), 1);
  });
  const [selectedDate, setSelectedDate] = useState<string>(formatDateKey(new Date()));
  const [participantNameInput, setParticipantNameInput] = useState("");
  const [myName, setMyName] = useState("");
  const [savedMyName, setSavedMyName] = useState("");
  const [availability, setAvailability] = useState<AvailabilityMap>({});
  const [draftAvailability, setDraftAvailability] = useState<PersonAvailability>({});
  const [isDirty, setIsDirty] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [saveMessage, setSaveMessage] = useState("");
  const [connectionStatus, setConnectionStatus] = useState<"online" | "local" | "error">("local");
  const [currentUserId, setCurrentUserId] = useState("");
  const [authReady, setAuthReady] = useState(false);

  const supabaseRef = useRef<SupabaseClient | null>(null);
  const activeParticipant = savedMyName || myName;

  useEffect(() => {
    setPollId(getPollId());
    supabaseRef.current = createSupabaseBrowserClient();
    setConnectionStatus(supabaseRef.current ? "online" : "local");
    setAuthReady(!supabaseRef.current);
  }, []);

  async function fetchAllAvailability(showRefreshing = false): Promise<void> {
    const supabase = supabaseRef.current;

    if (!supabase) {
      if (typeof window !== "undefined") {
        const localRaw = localStorage.getItem(getStorageKey(pollId));
        const local = localRaw ? JSON.parse(localRaw) : {};
        setAvailability(local.availability || {});
      }
      return;
    }

    if (showRefreshing) setIsRefreshing(true);

    const { data, error } = await supabase
      .from("meeting_availability")
      .select("participant_name, date_key, slots")
      .eq("poll_id", pollId);

    if (error) {
      setConnectionStatus("error");
      setSaveMessage("读取在线数据失败，请检查 Supabase 配置、RLS 或网络连接。");
    } else {
      setAvailability(inflateRowsToAvailability((data || []) as Array<{ participant_name: string; date_key: string; slots: string[] }>));
      setConnectionStatus("online");
    }

    if (showRefreshing) setIsRefreshing(false);
  }

  useEffect(() => {
    if (!pollId) return;
    let ignore = false;

    async function init(): Promise<void> {
      setIsLoading(true);

      if (typeof window !== "undefined") {
        const profileRaw = localStorage.getItem(getProfileKey(pollId));
        const profile = profileRaw ? JSON.parse(profileRaw) : {};
        const cachedName = profile.myName || "";
        if (!ignore) {
          setMyName(cachedName);
          setSavedMyName(cachedName);
          setParticipantNameInput(cachedName);
        }
      }

      const supabase = supabaseRef.current;
      if (supabase) {
        const {
          data: { session },
          error: sessionError,
        } = await supabase.auth.getSession();

        if (sessionError) {
          if (!ignore) {
            setConnectionStatus("error");
            setSaveMessage("读取登录状态失败，请检查 Supabase Auth 配置。");
            setAuthReady(false);
            setIsLoading(false);
          }
          return;
        }

        let activeSession = session;
        if (!activeSession) {
          const { data: anonData, error: anonError } = await supabase.auth.signInAnonymously();
          if (anonError) {
            if (!ignore) {
              setConnectionStatus("error");
              setSaveMessage("匿名登录失败，请先在 Supabase Auth 中启用 Anonymous sign-ins。");
              setAuthReady(false);
              setIsLoading(false);
            }
            return;
          }
          activeSession = anonData.session;
        }

        if (!ignore) {
          setCurrentUserId(activeSession?.user?.id || "");
          setAuthReady(Boolean(activeSession?.user?.id));
        }
      }

      await fetchAllAvailability(false);
      if (!ignore) setIsLoading(false);
    }

    void init();

    return () => {
      ignore = true;
    };
  }, [pollId]);

  useEffect(() => {
    if (!pollId || typeof window === "undefined") return;
    localStorage.setItem(getProfileKey(pollId), JSON.stringify({ myName }));
  }, [myName, pollId]);

  useEffect(() => {
    if (!savedMyName) {
      setDraftAvailability({});
      setIsDirty(false);
      return;
    }

    const committed = normalizePersonAvailability(availability[savedMyName] || {});
    setDraftAvailability(committed);
    setIsDirty(false);
  }, [availability, savedMyName]);

  useEffect(() => {
    if (!pollId || typeof window === "undefined") return;
    localStorage.setItem(getStorageKey(pollId), JSON.stringify({ availability, myName: savedMyName || myName }));
  }, [availability, savedMyName, myName, pollId]);

  useEffect(() => {
    const supabase = supabaseRef.current;
    if (!supabase || !pollId) return;

    const channel = supabase
      .channel(`meeting-poll-${pollId}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "meeting_availability",
          filter: `poll_id=eq.${pollId}`,
        },
        async () => {
          await fetchAllAvailability(false);
        }
      )
      .subscribe((status) => {
        if (status === "SUBSCRIBED") setConnectionStatus("online");
      });

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, session) => {
      setCurrentUserId(session?.user?.id || "");
      setAuthReady(Boolean(session?.user?.id));
      if (event === "SIGNED_OUT") {
        setSaveMessage("登录状态已失效，请刷新页面重新匿名登录。");
      }
    });

    return () => {
      void supabase.removeChannel(channel);
      subscription.unsubscribe();
    };
  }, [pollId]);

  const participants = useMemo(() => Object.keys(availability).sort(), [availability]);
  const monthLabel = `${currentMonth.getFullYear()} 年 ${currentMonth.getMonth() + 1} 月`;
  const weeks = useMemo(() => getMonthMatrix(currentMonth), [currentMonth]);
  const selectedSlots = draftAvailability[selectedDate] || [];

  const allDateSlotKeys = useMemo(() => {
    const keys = new Set<string>();
    Object.values(availability).forEach((personData) => {
      Object.entries(personData || {}).forEach(([dateKey, slots]) => {
        (slots || []).forEach((slot) => keys.add(`${dateKey}__${slot}`));
      });
    });
    return Array.from(keys).sort();
  }, [availability]);

  const commonSlots = useMemo(() => {
    if (participants.length === 0) return [] as Array<{ dateKey: string; slotId: string; slotLabel: string }>;

    return allDateSlotKeys
      .filter((key) => {
        const [dateKey, slotId] = key.split("__");
        return participants.every((person) => {
          const personSlots = availability[person]?.[dateKey] || [];
          return personSlots.includes(slotId);
        });
      })
      .map((key) => {
        const [dateKey, slotId] = key.split("__");
        return { dateKey, slotId, slotLabel: slotLabelById(slotId) };
      });
  }, [allDateSlotKeys, availability, participants]);

  const participantCountPerSlot = useMemo(() => {
    const map: Record<string, number> = {};
    allDateSlotKeys.forEach((key) => {
      const [dateKey, slotId] = key.split("__");
      map[key] = participants.filter((person) => (availability[person]?.[dateKey] || []).includes(slotId)).length;
    });
    return map;
  }, [allDateSlotKeys, availability, participants]);

  const participantSelections = useMemo(() => {
    return participants.map((name) => {
      const personData = availability[name] || {};
      const entries = Object.entries(personData)
        .filter(([, slots]) => Array.isArray(slots) && slots.length > 0)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([dateKey, slots]) => ({
          dateKey,
          labels: [...slots].sort().map((slotId) => slotLabelById(slotId)),
        }));

      return {
        name,
        entries,
        totalCount: entries.reduce((sum, item) => sum + item.labels.length, 0),
      };
    });
  }, [availability, participants]);

  function registerMe(): void {
    const trimmed = participantNameInput.trim();
    if (!trimmed) return;
    setMyName(trimmed);
    setSavedMyName(trimmed);
    setSaveMessage(`当前填写人已设置为 ${trimmed}。你现在只会编辑自己的时间。`);
  }

  function toggleSlot(slotId: string): void {
    if (!activeParticipant) return;
    const next = { ...draftAvailability };
    const existing = next[selectedDate] || [];
    const updated = existing.includes(slotId)
      ? existing.filter((s) => s !== slotId)
      : [...existing, slotId];

    if (updated.length === 0) {
      delete next[selectedDate];
    } else {
      next[selectedDate] = [...updated].sort();
    }

    setDraftAvailability(normalizePersonAvailability(next));
    setIsDirty(true);
    setSaveMessage("你有未保存的修改。仅会保存你自己的时间，不会覆盖其他人的数据。");
  }

  function clearSelectedDateForParticipant(): void {
    if (!activeParticipant) return;
    const next = { ...draftAvailability };
    delete next[selectedDate];
    setDraftAvailability(normalizePersonAvailability(next));
    setIsDirty(true);
    setSaveMessage("当前日期的选择已清空，记得点击保存。");
  }

  async function saveMyAvailability(): Promise<void> {
    const trimmedName = activeParticipant.trim();
    if (!trimmedName) {
      setSaveMessage("请先输入并确认你的姓名。");
      return;
    }

    const supabase = supabaseRef.current;
    if (supabase && (!authReady || !currentUserId)) {
      setSaveMessage("当前匿名登录尚未完成，请稍后再试。若一直失败，请在 Supabase 中启用 Anonymous sign-ins。");
      return;
    }

    const normalizedDraft = normalizePersonAvailability(draftAvailability);
    setIsSaving(true);
    setSaveMessage("");

    try {
      if (supabase) {
        const { data: myRows, error: fetchMineError } = await supabase
          .from("meeting_availability")
          .select("date_key")
          .eq("poll_id", pollId)
          .eq("owner_user_id", currentUserId);

        if (fetchMineError) throw fetchMineError;

        const savedDates = ((myRows || []) as Array<{ date_key: string }>).map((row) => row.date_key);
        const draftDates = Object.keys(normalizedDraft);
        const datesToDelete = savedDates.filter((dateKey) => !draftDates.includes(dateKey));

        if (datesToDelete.length > 0) {
          const { error: deleteError } = await supabase
            .from("meeting_availability")
            .delete()
            .eq("poll_id", pollId)
            .eq("owner_user_id", currentUserId)
            .in("date_key", datesToDelete);

          if (deleteError) throw deleteError;
        }

        const rowsToUpsert = flattenPersonAvailability(normalizedDraft, trimmedName, currentUserId, pollId);
        if (rowsToUpsert.length > 0) {
          const { error: upsertError } = await supabase
            .from("meeting_availability")
            .upsert(rowsToUpsert, { onConflict: "poll_id,participant_name,date_key" });

          if (upsertError) throw upsertError;
        }

        await fetchAllAvailability(false);
        setConnectionStatus("online");
      } else {
        setAvailability((prev) => ({
          ...prev,
          [trimmedName]: normalizedDraft,
        }));
        setConnectionStatus("local");
      }

      setSavedMyName(trimmedName);
      setMyName(trimmedName);
      setDraftAvailability(normalizedDraft);
      setIsDirty(false);
      setSaveMessage("已保存你的时间。现在会按当前匿名登录身份安全写入，不会覆盖其他参会人的内容。");
    } catch (error) {
      console.error(error);
      setConnectionStatus(supabase ? "error" : "local");
      setSaveMessage("保存失败，请检查 Supabase 表结构、RLS policy、匿名登录和网络连接。");
    } finally {
      setIsSaving(false);
    }
  }

  async function removeMyAvailability(): Promise<void> {
    const trimmedName = activeParticipant.trim();
    if (!trimmedName) return;

    const supabase = supabaseRef.current;
    if (supabase && (!authReady || !currentUserId)) {
      setSaveMessage("当前匿名登录尚未完成，暂时不能删除。请稍后再试。");
      return;
    }

    setIsSaving(true);
    try {
      if (supabase) {
        const { error } = await supabase
          .from("meeting_availability")
          .delete()
          .eq("poll_id", pollId)
          .eq("owner_user_id", currentUserId);
        if (error) throw error;
        await fetchAllAvailability(false);
      } else {
        setAvailability((prev) => {
          const next = { ...prev };
          delete next[trimmedName];
          return next;
        });
      }

      setDraftAvailability({});
      setIsDirty(false);
      setSaveMessage("已删除你当前匿名身份下保存的时间。其他参会人的数据不受影响。");
    } catch (error) {
      console.error(error);
      setSaveMessage("删除失败，请稍后重试。请确认 RLS policy 允许当前用户删除自己的记录。");
    } finally {
      setIsSaving(false);
    }
  }

  function goPrevMonth(): void {
    setCurrentMonth((prev) => new Date(prev.getFullYear(), prev.getMonth() - 1, 1));
  }

  function goNextMonth(): void {
    setCurrentMonth((prev) => new Date(prev.getFullYear(), prev.getMonth() + 1, 1));
  }

  function getHeatForDay(dateKey: string): number {
    if (participants.length === 0) return 0;
    let maxMatched = 0;
    TIME_SLOTS.forEach((slot) => {
      const count = participants.filter((p) => (availability[p]?.[dateKey] || []).includes(slot.id)).length;
      if (count > maxMatched) maxMatched = count;
    });
    return maxMatched;
  }

  const todayKey = formatDateKey(new Date());
  const mySavedAvailability = savedMyName ? normalizePersonAvailability(availability[savedMyName] || {}) : {};
  const hasServerDiff = savedMyName ? !arePersonAvailabilityEqual(mySavedAvailability, draftAvailability) : false;

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="grid gap-4 md:grid-cols-3">
          <Card className="rounded-2xl shadow-sm md:col-span-2">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-2xl">
                <CalendarDays className="h-6 w-6" />
                团队会议时间协调
              </CardTitle>
              <p className="text-sm text-slate-600">
                每位参会人只编辑并保存自己的可用时间。页面会自动匿名登录到 Supabase，再按当前身份安全保存并同步数据。
              </p>
            </CardHeader>
          </Card>

          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Cloud className="h-5 w-5" />
                同步状态
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center gap-2 text-sm">
                {connectionStatus === "online" ? (
                  <>
                    <Wifi className="h-4 w-4" />
                    <span>在线实时同步已启用</span>
                  </>
                ) : connectionStatus === "local" ? (
                  <>
                    <WifiOff className="h-4 w-4" />
                    <span>当前为本地演示模式</span>
                  </>
                ) : (
                  <>
                    <WifiOff className="h-4 w-4" />
                    <span>连接异常，在线同步不可用</span>
                  </>
                )}
              </div>

              <div className="rounded-xl bg-slate-100 p-3 text-sm text-slate-600">
                Poll ID：<span className="font-semibold">{pollId}</span>
              </div>

              <div className="rounded-xl bg-slate-100 p-3 text-sm text-slate-600">
                当前身份：<span className="font-semibold">{authReady && currentUserId ? `${currentUserId.slice(0, 8)}…` : "未就绪"}</span>
              </div>

              <Button variant="outline" className="w-full gap-2" onClick={() => void fetchAllAvailability(true)} disabled={isRefreshing || isLoading}>
                <RefreshCw className={`h-4 w-4 ${isRefreshing ? "animate-spin" : ""}`} />
                {isRefreshing ? "刷新中…" : "手动刷新在线数据"}
              </Button>
            </CardContent>
          </Card>
        </motion.div>

        {!supabaseRef.current && (
          <Alert className="rounded-2xl border-amber-200 bg-amber-50">
            <AlertDescription className="text-sm leading-6 text-amber-900">
              还未配置 NEXT_PUBLIC_SUPABASE_URL 和 NEXT_PUBLIC_SUPABASE_ANON_KEY。当前页面可本地演示，但不会真的多人在线同步。
            </AlertDescription>
          </Alert>
        )}

        <div className="grid gap-6 lg:grid-cols-[1.3fr_0.9fr]">
          <Card className="rounded-2xl shadow-sm">
            <CardHeader>
              <div className="flex items-center justify-between gap-2">
                <CardTitle className="text-xl">选择日期</CardTitle>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="icon" onClick={goPrevMonth}>
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <div className="min-w-[120px] text-center font-medium">{monthLabel}</div>
                  <Button variant="outline" size="icon" onClick={goNextMonth}>
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-7 gap-2 text-center text-sm text-slate-500">
                {WEEKDAYS.map((day) => (
                  <div key={day} className="py-2 font-medium">
                    {day}
                  </div>
                ))}
              </div>
              <div className="mt-2 grid gap-2">
                {weeks.map((week, i) => (
                  <div key={String(i)} className="grid grid-cols-7 gap-2">
                    {week.map((date) => {
                      const dateKey = formatDateKey(date);
                      const inCurrentMonth = date.getMonth() === currentMonth.getMonth();
                      const isSelected = dateKey === selectedDate;
                      const isToday = dateKey === todayKey;
                      const heat = getHeatForDay(dateKey);

                      return (
                        <button
                          key={dateKey}
                          onClick={() => setSelectedDate(dateKey)}
                          className={`min-h-[84px] rounded-2xl border p-2 text-left transition hover:shadow-sm ${
                            isSelected ? "border-2 border-emerald-500 bg-white ring-2 ring-emerald-100" : "border-slate-200 bg-white"
                          } ${!inCurrentMonth ? "opacity-40" : "opacity-100"}`}
                        >
                          <div className="flex items-center justify-between">
                            <span className="text-sm font-medium">{date.getDate()}</span>
                            <div className="flex items-center gap-1">
                              {isToday && <Badge variant="secondary">今天</Badge>}
                              {heat > 0 && <Badge variant="outline">{heat}人可选</Badge>}
                            </div>
                          </div>
                          <div className="mt-3 space-y-1">
                            {TIME_SLOTS.map((slot) => {
                              const key = `${dateKey}__${slot.id}`;
                              const count = participantCountPerSlot[key] || 0;
                              if (count === 0) return null;
                              return (
                                <div key={slot.id} className="text-[11px] text-slate-700">
                                  {slot.label.split(" ")[0]}：{count}/{participants.length || 0}
                                </div>
                              );
                            })}
                          </div>
                        </button>
                      );
                    })}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <div className="space-y-6">
            <Card className="rounded-2xl shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <User className="h-5 w-5" />
                  我来填写
                </CardTitle>
                <p className="text-sm text-slate-600">先输入你的显示姓名。真正的写入权限由 Supabase 匿名登录身份控制。</p>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex gap-2">
                  <Input value={participantNameInput} onChange={(e) => setParticipantNameInput(e.target.value)} placeholder="输入你的姓名" onKeyDown={(e) => e.key === "Enter" && registerMe()} />
                  <Button onClick={registerMe}>确认身份</Button>
                </div>

                {savedMyName ? (
                  <div className="rounded-xl bg-slate-100 p-3 text-sm text-slate-700">
                    当前填写人：<span className="font-semibold">{savedMyName}</span>
                  </div>
                ) : (
                  <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">先确认你的姓名，然后再勾选时间。</div>
                )}
              </CardContent>
            </Card>

            <Card className="rounded-2xl shadow-sm">
              <CardHeader>
                <CardTitle className="text-xl">填写可用时间</CardTitle>
                <p className="text-sm text-slate-600">当前日期：{formatDateCN(selectedDate)}</p>
              </CardHeader>
              <CardContent className="space-y-4">
                {isLoading || (supabaseRef.current && !authReady) ? (
                  <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">正在准备数据和匿名登录…</div>
                ) : !savedMyName ? (
                  <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">请先确认你的姓名。</div>
                ) : (
                  <>
                    <div className="space-y-3">
                      {TIME_SLOTS.map((slot) => {
                        const checked = selectedSlots.includes(slot.id);
                        return (
                          <label key={slot.id} className="flex cursor-pointer items-center justify-between rounded-xl border p-3 hover:bg-slate-50">
                            <div>
                              <div className="font-medium">{slot.label}</div>
                              <div className="text-sm text-slate-500">勾选这个时间段表示你可以参加会议</div>
                            </div>
                            <Checkbox checked={checked} onCheckedChange={() => toggleSlot(slot.id)} />
                          </label>
                        );
                      })}
                    </div>

                    <div className="flex gap-2">
                      <Button variant="outline" className="flex-1" onClick={clearSelectedDateForParticipant}>
                        清空当天选择
                      </Button>
                      <Button variant="destructive" className="flex-1" onClick={() => void removeMyAvailability()} disabled={isSaving || !savedMyName}>
                        删除我的全部时间
                      </Button>
                    </div>

                    <Button className="w-full gap-2" onClick={() => void saveMyAvailability()} disabled={isSaving || !savedMyName || !isDirty}>
                      <Save className="h-4 w-4" />
                      {isSaving ? "保存中…" : isDirty ? "保存我的选择" : "已保存"}
                    </Button>

                    {hasServerDiff && !isDirty && (
                      <div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">你的本地草稿与服务器数据不一致，建议重新勾选并保存。</div>
                    )}
                  </>
                )}

                {saveMessage && <div className="rounded-xl bg-slate-100 p-3 text-sm text-slate-600">{saveMessage}</div>}
              </CardContent>
            </Card>

            <Card className="rounded-2xl shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <CheckCircle2 className="h-5 w-5" />
                  自动匹配结果
                </CardTitle>
              </CardHeader>
              <CardContent>
                {participants.length === 0 ? (
                  <p className="text-sm text-slate-500">还没有任何人保存时间。</p>
                ) : commonSlots.length === 0 ? (
                  <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">当前还没有找到所有人都可以的共同时间。</div>
                ) : (
                  <div className="space-y-3">
                    {commonSlots.map((item) => (
                      <motion.div key={`${item.dateKey}-${item.slotId}`} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border bg-slate-50 p-3">
                        <div className="font-medium">{formatDateCN(item.dateKey)}</div>
                        <div className="mt-1 text-sm text-slate-600">{item.slotLabel}</div>
                        <div className="mt-2 text-xs text-slate-500">所有 {participants.length} 位已保存参会人都有空</div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>

        <Card className="rounded-2xl shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-xl">
              <Users className="h-5 w-5" />
              已参与的参会人
            </CardTitle>
          </CardHeader>
          <CardContent>
            {participants.length === 0 ? (
              <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">暂无参会人。</div>
            ) : (
              <div className="flex flex-wrap gap-2">
                {participants.map((name) => (
                  <Badge key={name} variant={name === savedMyName ? "default" : "secondary"}>
                    {name}
                  </Badge>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="rounded-2xl shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-xl">
              <UserCheck className="h-5 w-5" />
              各参会人已保存时间
            </CardTitle>
            <p className="text-sm text-slate-600">这里只展示已经保存到系统的数据。</p>
          </CardHeader>
          <CardContent>
            {participants.length === 0 ? (
              <div className="rounded-xl border border-dashed p-4 text-sm text-slate-500">暂无已保存的参会人信息。</div>
            ) : (
              <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {participantSelections.map((person) => (
                  <div key={person.name} className="rounded-2xl border bg-white p-4 shadow-sm">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-base font-semibold">{person.name}</div>
                      <Badge variant="secondary">已保存 {person.totalCount} 项</Badge>
                    </div>

                    {person.entries.length === 0 ? (
                      <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-500">该参会人还没有保存时间。</div>
                    ) : (
                      <div className="mt-4 space-y-3">
                        {person.entries.map((entry) => (
                          <div key={`${person.name}-${entry.dateKey}`} className="rounded-xl bg-slate-50 p-3">
                            <div className="text-sm font-medium">{formatDateCN(entry.dateKey)}</div>
                            <div className="mt-2 flex flex-wrap gap-2">
                              {entry.labels.map((label) => (
                                <Badge key={`${entry.dateKey}-${label}`} variant="outline">
                                  {label}
                                </Badge>
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
